Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -35,18 +35,18 @@ jobs:
           tags: "wessupplychain/test:${{ github.sha }}"
       - name: Manifest Generation
         run: |
-        export BILLY_SERVER=https://prod-aqua-billy.codesec.aquasec.com
-        curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
-        curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-        if ! cat install.sh.checksum | sha256sum ; then
-        echo "install.sh checksum failed"
-        exit 1
-        fi
-        sh install.sh
-        rm install.sh install.sh.checksum
-        billy generate \
-        --access-token "${{ secrets.GITHUB_TOKEN }}" \
-        --aqua-key "${{ secrets.AQUA_KEY }}" \
-        --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-        --cspm-url "https://api.cloudsploit.com" \
-        --artifact-path "wessupplychain/test:${{ env.tag-version }}" 
+          export BILLY_SERVER=https://prod-aqua-billy.codesec.aquasec.com
+          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+          if ! cat install.sh.checksum | sha256sum ; then
+            echo "install.sh checksum failed"
+            exit 1
+          fi
+          sh install.sh
+          rm install.sh install.sh.checksum
+          billy generate \
+              --access-token "${{ secrets.GITHUB_TOKEN }}" \
+              --aqua-key "${{ secrets.AQUA_KEY }}" \
+              --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+              --cspm-url "https://api.cloudsploit.com" \
+              --artifact-path "wessupplychain/test:${{ github.sha }}"
